import Foundation

/// A type that can be generated by a language model.
///
/// Types conforming to `Generable` can be used with `LanguageModelSession.respond(to:generating:)`
/// to generate structured output from a language model.
public protocol Generable: ConvertibleFromGeneratedContent,
                           ConvertibleToGeneratedContent {

    /// A representation of partially generated content
    associatedtype PartiallyGenerated: ConvertibleFromGeneratedContent = Self

    /// An instance of the generation schema.
    static var generationSchema: GenerationSchema { get }
}

extension Generable {
    
    /// The partially generated type of this struct.
    public func asPartiallyGenerated() -> Self.PartiallyGenerated {
        // Default implementation - works when PartiallyGenerated == Self
        return self as! Self.PartiallyGenerated
    }
}

extension Generable {
    
    /// A representation of partially generated content
    public typealias PartiallyGenerated = Self
}

